name: Build and publish image

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * 0'

jobs:

  build-and-publish-image:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run:
          docker image build
            --tag ghcr.io/acceptablesoftware/python-testing-environment
            ./src

      - name: Publish image
        run:
          docker push
            ghcr.io/acceptablesoftware/python-testing-environment
